Taywee/args

args.hxx

Compilation using Intel C++ 2016 Update 3 currently fails due to a stricter requirement that all definitions within a class must only be used after they have been defined earlier in the header/source file.
Moving the validator definition a few lines earlier in the code fixes the issue.

validators must be defined earlier for compilation with Intel C++

---

args.hxx

**args.hxx** has many places where method parameter names or local variables shadow class member names. In all cases they are properly disambiguated by using **this->** for class member access, so there is no functional problem. But Visual Studio issues warnings, a lot of them. 
This commit makes no functional changes, but it renames several variables to eliminate warnings:
- Append '_' to all method parameters with names that shadow class members.
- Rename three local variables with names that shadow class members.

Fix for many warnings in Visual Studio

---

args.hxx
test.cxx

This was discussed in #7. I propose following syntax:
```c++
try
{
args::ArgumentParser parser("");
args::ValueFlag<int> integer(parser, "integer", "The integer flag", {'i'}, args::Options::Required | args::Options::Single);
args::Positional<std::string> foo(parser, "foo", "The foo position", args::Options::Required);
parser.ParseCLI(argc, argv);
}
catch (args::RequiredError &e)
{
std::cerr << e.what() << std::endl;
}
```
`Options::Single` can be used instead of `extraError` boolean flag.
I think that in some cases *required* option is better than group validation, because:
- it is easier to give a nice message
- we can use this information to get a better progline

Required flags

---

args.hxx
test.cxx

Solves problem from #32. Flags or positional with `args::Options::Hidden` won't appear in help output.
```c++
args::ValueFlag<int> foo("foo", "foo", {'f'}, args::Options::Hidden);
```

Add Options::Hidden to exclude option from help

---

args.hxx
test.cxx

Implicit value flags:
```c++
ImplicitValueFlag<int> threads(parser, "", "", {'j'}, std::hardware_concurrency(), 1);
```
Nargs value flags:
```c++
NargsValueFlag<int> cpCommand(parser, "", "", {"cp"}, 2);
```
These flags should be used very carefully for reasons described in #33. But there are use cases (`-j` in particular).
I also refactored `ParseArgs()`. It was confusing to say the least.

Imlicit values and nargs

---

args.hxx
test.cxx

I've improved help output for commands. Commands have description and epilogue just as ArgumentParser. Help exception can be handled at top-level command since `stream << argumentParser` will print help page for selected command.
There are also `showCommandChildren` and `showCommandFullHelp` modes (not sure about the names, any ideas?). They might be useful when your app has a few commands and default mode will print not informative help message.
In these modes `Subparser::Parse` will throw `Help` exception to get descriptions from subparser. I will change it to some `InternalHelp` in next PR about validation and error handling in commands.

Subparsers help

---

.gitignore
.travis.yml
CMakeLists.txt
README.md
appveyor.yml
args.hxx
catch.hpp
test.cxx

To be sure that PR won't break any build or tests.
I had to update catch, since older versions [had certain problems](https://github.com/catchorg/Catch2/pull/728) with msvc /W3 or higher.
I've also added CMakeLists.txt to make compilation in Windows easier. We can reuse CMake to test inclusion of `args.hxx` into multiple sources or compilation with `-fno-exceptions -fno-rtti`.
If everything is fine, you need to set up Travis CI, Appveyor CI and Coveralls and fix links in `README.md`.

Add Travis CI, Appveyor, Coveralls and fix gcc, clang, msvc warnings

---

.travis.yml
args.hxx

Fixes an access to uninitialized `bool ArgumentParser::allowJoinedLongValue`. I found it with ubsan, so I suggest using it and asan in Travis CI.

Fix uninitialized values

---

args.hxx
test.cxx

`HelpParams::proglineShowFlags` adds actual flags instead of string '{OPTIONS}'. Flags are added as `--value-flag <NAME>` or `--bool-flag`. Non-required flags are surrounded by brackets.
`HelpParams::proglinePreferShortFlags` tries to use short flag names in usage.
I also removed brackets for required positional arguments.

Add HelpParams::proglineShowFlags

---

args.hxx
test.cxx

`usageStrings` can be used to add prefix to program line, e.g. `usage: `.
`optionsString` allows you to change default `OPTIONS:` string in help output.
`useValueNameOnce` hides multiple value names from description: `-f[FILE], --file=[FILE]` vs `-f, --file=[FILE]`.
`showValueName` allows you to hide value names.
`addNewlineBeforeDescription` adds a newline before flag description.
Wrap now don't trim leading whitespace. Indenting lines in description might be useful.

Add more help parameters

---

args.hxx
test.cxx

Fixes #27. Adds simple ActionFlag that calls a function.
```c++
args::ActionFlag version(parser, "version", "show version", {'v', "version"}, []() { throw Version(); });
```
You can also define "value-accepting" ActionFlag by changing function argument type.
```c++
args::ActionFlag noArg(..., []() { });
args::ActionFlag oneArg(..., [](const std::string &) { });
args::ActionFlag nArgs(..., args::Nargs(2), [](const std::vector<std::string> &) { });
```

ActionFlag

---

README.md

I added two examples for new commands feature: the first one has everything in one function and the second one uses lambdas and functions.

Add examples for commands

---

CMakeLists.txt
args.hxx
test.cxx

Fixes #6, #25.
Set `HelpParams::addDefault` and `HelpParams::addChoices` to enable auto-generated default/choices strings globally. Use `NamedBase::HelpDefault(string)` and `NamedBase::HelpChoices(string)` to enable/disable it.

Add default values and choices to help output

---

args.hxx
test.cxx

Fixes #17. It allows you to use `ValueFlag<std::filesystem::path>`, `ValueFlagList<SomeCustomTypeAssignableToString>`, etc.

Fix ValueReader for types assignable to std::string

---

Makefile
args.hxx
test.cxx

New `proglineShowFlags=true` feature doesn't look nice with wrapping:
```bash
myprog [--foo <foo>] [--bar <bar>] [--baz
<baz>]
```
I fixed this by wrapping usage line by "tokens".
```bash
myprog [--foo <foo>] [--bar <bar>]
[--baz <baz>]
```

Fix usage line wrapping

---

args.hxx
test.cxx

Split `Options::Hidden` into `Options::HiddenFromUsage` and `Options::HiddenFromDescription`.
The main use case for `HiddenFromDescription` is hiding positional options. `HiddenFromUsage` could be used to leave only the most important options in usage line, otherwise it would be too long.

Add Options::HiddenFromUsage and Options::HiddenFromDescription

---

.buckconfig
.gitignore
BUCK
examples/BUCK
test/BUCK

Hello 😄! 
This PR adds support for the [Buck](https://buckbuild.com) build system. Whilst this library is header-only, the Buck file serves as instructions for integrating the headers into other libraries. I also ported the tests + examples. The existing Make build is left unchanged. 
https://github.com/LoopPerfect/buckaroo-wishlist/issues/85

Buck build support

---

args.hxx

These get flagged by recent versions of GCC and Clang when building
with -Wsign-conversion.

Remove signed <-> unsigned warnings around size_t

---

CMakeLists.txt

I hard coded the destination to install, but this is good enough for vcpkg to consume:
```
The package args:x86-windows provides CMake targets:
find_package(args CONFIG REQUIRED)
target_link_libraries(main PRIVATE taywee::args)
```
(I hacked both repos, obviously, but you get the idea.)

install CMake target taywee::args

---

args.hxx
test.cxx

Fixes #75 
BTW, @Taywee, is this `std::ws` part in ValueParser really necessary? It seems strange to have command line like `-i '42 '`.

Check istringstream state in ValueParser

---

args.hxx

Makes it easier to find this repository if you copied the header file into your project without the readme.

Update copyright year, add description and URL

---

args.hxx

Fix the three warnings below. This fixes Issue #88 (noexcept). Not sure if the signed/unsigned char fix is ok for platforms other than Windows.
Utilities\DxFileUtility\DxFileUtility\args.hxx (232, 0)
Utilities\DxFileUtility\DxFileUtility\args.hxx(232,0): Warning C6330: 'char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.
Utilities\DxFileUtility\DxFileUtility\args.hxx (466, 0)
Utilities\DxFileUtility\DxFileUtility\args.hxx(466,0): Warning C26439: This kind of function may not throw. Declare it 'noexcept' (f.6).
Utilities\DxFileUtility\DxFileUtility\args.hxx (2021, 0)
Utilities\DxFileUtility\DxFileUtility\args.hxx(2021,0): Warning C6330: 'char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.

Fix static code analysis warnings in Visual Studio 2019

---

CMakeLists.txt

Most of downstream distribution systems prefer using ports rather than fetching anything during the build. FTXUI depends on args via FetchContent. CMake 3.24 support FIND_PACKAGE_ARGS to allow installed packages to override fetch_content.
My problem is that `taywee::args` is only exported when installed, but only as "args" when used
as a subproject.
This patch exports `taywee::args` so that the same name can be used in both cases.
Bug:https://github.com/ArthurSonzogni/json-tui/issues/32

Export taywee::args
